project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!ClassCode/"

website:
  title: "Research for Public Policy"
  navbar:
    left:
      - href: index.qmd
        text: " "
        icon: house
      - href: syllabus.qmd
        text: Syllabus
      - href: slides.qmd
        text: Lecture Slides
      - href: rcode.qmd
        text: R Code
      - href: problemsets.qmd
        text: Problem Sets
      - href: project.qmd
        text: Final Project
      - href: resources.qmd
        text: Resources
  favicon: /images/Clipboard.svg

format:
  html:
    theme: cosmo
    css: styles.css  
    toc: true
    toc-depth: 3
    highlight-style: github
    code-copy: true
    code-overflow: wrap

editor: visual
resources:
    - "/ClassCode"
    - "/problemsets"
    - "/CNAME"
